# Generated by Django 5.0.14 on 2026-05-30 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام شرکت / صنف')),
                ('mobile', models.CharField(max_length=15, unique=True, verbose_name='شماره موبایل')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='نشانی ایمیل')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت (فعال/غیرفعال)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
            },
        ),
        migrations.CreateModel(
            name='GatewaySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bale_bot_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='توکن ربات بله')),
                ('bale_chat_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='شناسه کانال یا چت ادمین')),
                ('kavenegar_api_url', models.CharField(default='https://api.kavenegar.com/v1', max_length=255, verbose_name='آدرس وب\u200cسرویس پیامک')),
                ('kavenegar_secret_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='کلید وب\u200cسرویس')),
                ('kavenegar_pattern', models.CharField(default='rooydad-expiry-alert', max_length=255, verbose_name='کد قالب')),
                ('kavenegar_sender', models.CharField(default='10008585', max_length=20, verbose_name='خط فرستنده')),
            ],
            options={
                'verbose_name': 'تنظیمات درگاه',
                'verbose_name_plural': 'تنظیمات درگاه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('domain', 'ثبت/تمدید دامنه'), ('server', 'سرور (اختصاصی/ابری)'), ('ssl', 'گواهینامه SSL')], max_length=20, verbose_name='نوع سرویس')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان سرویس یا دامنه')),
                ('provider', models.CharField(max_length=255, verbose_name='کارگزار / ارائه\u200cدهنده مرجع')),
                ('buy_price', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='بهای تمام\u200cشده برای شما (تومان)')),
                ('sell_price', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='بهای فروش به مشتری (تومان)')),
                ('payment_status', models.CharField(choices=[('pending', 'در انتظار تایید پرداخت'), ('paid', 'پرداخت شده / تسویه')], default='pending', max_length=20, verbose_name='وضعیت پرداخت و فاکتور')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع / ثبت فاکتور')),
                ('end_date', models.DateField(verbose_name='تاریخ سررسید / انقضا')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.customer', verbose_name='مشتری بهره\u200cبردار')),
            ],
            options={
                'verbose_name': 'سرویس',
                'verbose_name_plural': 'سرویس\u200cها',
                'ordering': ['end_date'],
            },
        ),
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('sms', 'ارسال پیامکی (Kavenegar)'), ('bale', 'پیام\u200cرسان بله (Bale)')], max_length=10, verbose_name='نوع هشدار')),
                ('message', models.TextField(verbose_name='متن پیام ارسال شده')),
                ('is_successful', models.BooleanField(default=True, verbose_name='وضعیت ارسال')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='services.serviceitem', verbose_name='سرویس مربوطه')),
            ],
            options={
                'verbose_name': 'تاریخچه هشدار',
                'verbose_name_plural': 'تاریخچه هشدارها',
            },
        ),
    ]
