# Generated by Django 5.0.14 on 2026-05-31 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='receive_alerts',
            field=models.BooleanField(default=True, verbose_name='ارسال خودکار پیامک هشدار'),
        ),
        migrations.CreateModel(
            name='ServiceRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ پرداختی (تومان)')),
                ('payment_date', models.DateField(verbose_name='تاریخ پرداخت')),
                ('new_end_date', models.DateField(verbose_name='سررسید جدید تخصیص یافته')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='services.serviceitem', verbose_name='سرویس مربوطه')),
            ],
            options={
                'verbose_name': 'تاریخچه تمدید',
                'verbose_name_plural': 'تاریخچه تمدیدها',
                'ordering': ['-payment_date'],
            },
        ),
    ]
