# Generated by Django 5.0.14 on 2026-05-31 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_customer_receive_alerts_servicerenewal'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات تکمیلی'),
        ),
        migrations.AddField(
            model_name='servicerenewal',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات پرداخت'),
        ),
    ]
